--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
 SUM(purchase_amount) AS total_revenue
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset` 
group by
  gender
order by 
total_revenue desc;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount 
from `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`
where discount_applied = TRUE
 and purchase_amount >= (
    select avg(purchase_amount) 
    from customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset
    );

--Q3. Which are the top 5 products with the highest average review rating? -
select item_purchased,round(AVG(review_rating),2) as avg_review_rating
from `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset` 
group by
item_purchased
order by avg_review_rating desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
  ROUND( AVG(purchase_amount),2) As avg_purchase_amount
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`
WHERE shipping_type in ("Standard","Express")
GROUP BY
  shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
  COUNT(customer_id) AS Total_customer,
  ROUND(AVG(purchase_amount),2) AS avg_spend,
  SUM(purchase_amount) AS total_revenue,
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`  
GROUP BY
  subscription_status
ORDER BY
total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT  item_purchased,
  ROUND( 100 * SUM(CASE WHEN(discount_applied = TRUE) THEN 1 ELSE 0 End)/count(*),2) ,
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`  
GROUP BY
  item_purchased
ORDER BY
  2 DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show-the count of each segment.
WITH customer_type as (
  SELECT customer_id,previous_purchases,
  CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN Previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE "Loyal"
    END AS  customer_segment
  FROM customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset
)

SELECT customer_segment,
  COUNT(customer_id) As Number_of_customers,
FROM customer_type
GROUP BY
  customer_segment
order by
  Number_of_customers desc;

--Q8. What are the top 3 mose purchased products within each category?

WITH item_counts AS(
  SELECT category,
    item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() over(partition by(category) ORDER BY count(customer_id) DESC ) as item_rank
  FROM`customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`   
GROUP BY
  category,
  item_purchased  
)

SELECT item_rank,category,
  item_purchased,
  total_orders
FROM item_counts
WHERE
  item_rank <=3  ;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
  count(customer_id) as repeat_customers
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`
WHERE
 previous_purchases > 5
GROUP BY
  subscription_status ;


--Q10. What is the revenue contribution of each age group?

SELECT age_group,
  SUM(purchase_amount) AS Total_revenue
FROM `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`
GROUP BY
  age_group
ORDER BY
  Total_revenue DESC;  

# split of gender
select gender, count (customer_id)
from customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset
group by
gender ;
# Male	2652	Female	1248

#Number of subcription bases on gender
SELECT subscription_status,
  gender,
  COUNT(customer_id) As Total_number
FROM  `customer-shopping-behaviour.customer_shopping_behaviour.cleaned_Shopping_dataset`
GROUP BY
  subscription_status,
  gender
ORDER BY
  Total_number DESC ;






















































